---
- name: implementing loops
  hosts: all
  tasks:
    - name: downloading multiple apps
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - maven
        - git
        - tree


...
