---
- name: configure tomcat
  hosts: all
  tasks:
    - name: tomcat installation
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: restart tomcat10
      service:
        name: tomcat10
        state: restarted
...
